import Head from 'next/head'
import Timer from '../Component/Timer'


export default function Home() {
  return (
    <div >
      <Head>
        <title>Survey</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <main className="main">
<Timer />

    </main>

    </div>
  )
}
